
import React from 'react';
import { Shield, Lock, FileText, Scale, X, CheckCircle2, AlertTriangle, Fingerprint, Database, Globe } from 'lucide-react';

interface LegalPageProps {
  type: 'privacy' | 'terms' | 'cookies';
  onClose: () => void;
}

const Section: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => (
  <div className="space-y-4">
    <h3 className="text-sm font-bold text-fcSlate uppercase tracking-widest flex items-center space-x-2">
      <div className="w-1.5 h-1.5 bg-fcGold rounded-full"></div>
      <span>{title}</span>
    </h3>
    <div className="text-sm text-gray-600 leading-relaxed font-medium space-y-4">
      {children}
    </div>
  </div>
);

export const LegalPages: React.FC<LegalPageProps> = ({ type, onClose }) => {
  const content = {
    privacy: {
      title: "Privacy & Data Sovereignty",
      subtitle: "Compliance with Cyber and Data Protection Act [Chapter 12:07]",
      icon: <Shield size={24} />,
      sections: [
        {
          title: "Statutory Framework",
          content: "Fine & Country Zimbabwe ERP operates under the strict guidelines of the Cyber and Data Protection Act [Chapter 12:07] and aligned with international GDPR standards. We act as both Data Controller and Data Processor for all real estate transactions within the Zimbabwe Regional Node."
        },
        {
          title: "KYC Data Collection",
          content: "To facilitate property transfers, we collect and forensically verify 'Know Your Customer' data including National Identity documents, Proof of Residence, and AML (Anti-Money Laundering) declarations. This data is stored within our 256-bit encrypted Document Vault."
        },
        {
          title: "Forensic Audit Trail",
          content: "Every mutation of your personal or financial data is recorded in an Immutable Forensic Audit Trail. This log captures the timestamp, terminal IP, and the identity of the authorized agent performing the mutation, ensuring total transparency and security."
        },
        {
          title: "Regulatory Sharing",
          content: "Data is only shared with authorized legal practitioners (Conveyancers) and regulatory bodies such as the Estate Agents Council of Zimbabwe (EACZ) for the explicit purpose of statutory property transfer and deed registration."
        }
      ]
    },
    terms: {
      title: "Transactional Terms of Service",
      subtitle: "Operational Integrity & Legal Jurisdiction",
      icon: <Scale size={24} />,
      sections: [
        {
          title: "Personnel Conduct",
          content: "Authorized Agents and Managers are strictly prohibited from sharing access credentials. Personnel activity is monitored by biometric and VPC cluster validation. Unauthorized attempts to export the Purchaser Registry will trigger immediate administrative alerts."
        },
        {
          title: "Digital Accuracy Clause",
          content: "Amortization Schedules and Statements of Account generated by the Fine & Country Zimbabwe ERP are based on automated financial logic and current statutory rates. All system-generated outputs are subject to final audit by our Finance and Legal divisions before deed execution."
        },
        {
          title: "Force Termination",
          content: "Fine & Country Zimbabwe ERP reserves the right to execute a 'Force Termination' of any user session or access tier if a security breach or policy violation is detected. This protocol is in place to protect the integrity of the Purchaser Registry and forensic ledger."
        },
        {
          title: "Governing Law",
          content: "These terms and all transactions facilitated by this platform are governed exclusively by the Laws of the Republic of Zimbabwe. Any disputes shall be settled within the jurisdiction of the High Court of Zimbabwe."
        }
      ]
    },
    cookies: {
      title: "Cookie & Session Logic",
      subtitle: "Zero-Tracking Security Policy",
      icon: <Database size={24} />,
      sections: [
        {
          title: "Essential Session Cookies",
          content: "The ERP utilizes essential session cookies to maintain your Secure Login state and Role-Based Access Control (RBAC) parameters. These are critical for navigating between the Dashboard, Inventory Plotting, and Financial Gateways."
        },
        {
          title: "Zero Third-Party Tracking",
          content: "In alignment with our security-first posture, this internal portal does not utilize third-party tracking, advertising, or analytics cookies. Your activity is not shared with external advertising networks."
        },
        {
          title: "Persistence Logic",
          content: "Cookies used by this platform are encrypted and expire automatically upon session termination or after a period of administrative inactivity to prevent unauthorized terminal hijacking."
        }
      ]
    }
  };

  const active = content[type];

  return (
    <div className="fixed inset-0 z-[110] flex items-center justify-center p-4 lg:p-12">
      <div 
        className="absolute inset-0 bg-fcSlate/80 backdrop-blur-md animate-in fade-in duration-500" 
        onClick={onClose} 
      />
      
      <div className="relative bg-fcCream w-full max-w-4xl max-h-[90vh] rounded-[40px] shadow-[0_30px_100px_-20px_rgba(0,0,0,0.5)] flex flex-col overflow-hidden animate-in zoom-in-95 duration-500">
        {/* Header */}
        <div className="bg-white px-10 py-12 border-b border-fcDivider flex justify-between items-center shrink-0">
          <div className="flex items-center space-x-6">
            <div className="p-4 bg-fcGold text-white rounded-2xl shadow-xl shadow-fcGold/20">
              {active.icon}
            </div>
            <div>
              <h2 className="text-3xl font-bold tracking-tightest text-fcSlate leading-none mb-2">{active.title}</h2>
              <p className="text-[10px] font-bold text-fcGold uppercase tracking-[0.3em]">{active.subtitle}</p>
            </div>
          </div>
          <button 
            onClick={onClose}
            className="p-3 bg-fcCream text-gray-600 hover:text-fcSlate rounded-full transition-all"
          >
            <X size={20} />
          </button>
        </div>

        {/* Scrollable Content */}
        <div className="flex-1 overflow-y-auto p-12 lg:px-24 space-y-16 no-scrollbar">
          {active.sections.map((section, idx) => (
            <Section key={idx} title={section.title}>
              <p>{section.content}</p>
            </Section>
          ))}

          {/* Compliance Badge */}
          <div className="pt-12 border-t border-fcDivider flex flex-col md:flex-row items-center justify-between gap-8 opacity-60">
            <div className="flex items-center space-x-3">
              <Shield size={16} className="text-fcGold" />
              <span className="text-[10px] font-bold text-gray-600 uppercase tracking-widest">Forensic Integrity Verified</span>
            </div>
            <div className="flex items-center space-x-4">
              <Fingerprint size={16} className="text-slate-300" />
              <div className="w-[1px] h-4 bg-slate-200" />
              <span className="text-[9px] font-mono text-gray-600 tracking-tighter uppercase">Checksum: {Math.random().toString(16).substr(2, 8).toUpperCase()}</span>
            </div>
          </div>
        </div>

        {/* Action Bar */}
        <div className="bg-white p-8 border-t border-fcDivider flex justify-center shrink-0">
          <button 
            onClick={onClose}
            className="bg-fcSlate text-white px-12 py-4 rounded-2xl text-[11px] font-bold uppercase tracking-[0.3em] shadow-xl hover:bg-white transition-all flex items-center space-x-3"
          >
            <CheckCircle2 size={16} />
            <span>Acknowledge & Close</span>
          </button>
        </div>
      </div>
    </div>
  );
};