/**
 * Standardized Error Codes
 * 
 * Provides consistent error codes for all API responses.
 * Used with apiError() helper for programmatic error handling.
 * 
 * @module lib/error-codes
 */

export const ErrorCodes = {
  // Authentication & Authorization (401-403)
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_FAILED: 'AUTH_FAILED',
  PASSWORD_COMPLEXITY: 'PASSWORD_COMPLEXITY',
  PASSWORD_REUSE: 'PASSWORD_REUSE',
  ADMIN_REQUIRED: 'ADMIN_REQUIRED',
  MANAGER_REQUIRED: 'MANAGER_REQUIRED',
  AGENT_REQUIRED: 'AGENT_REQUIRED',
  ACCOUNTANT_REQUIRED: 'ACCOUNTANT_REQUIRED',
  ACCESS_DENIED: 'ACCESS_DENIED',
  RATE_LIMIT: 'RATE_LIMIT',

  // Validation Errors (400)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_REQUEST: 'INVALID_REQUEST',
  INVALID_ID: 'INVALID_ID',
  PARSE_ERROR: 'PARSE_ERROR',
  MISSING_FIELDS: 'MISSING_FIELDS',
  INVALID_FORMAT: 'INVALID_FORMAT',

  // Not Found (404)
  NOT_FOUND: 'NOT_FOUND',
  STAND_NOT_FOUND: 'STAND_NOT_FOUND',
  DEVELOPMENT_NOT_FOUND: 'DEVELOPMENT_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  CLIENT_NOT_FOUND: 'CLIENT_NOT_FOUND',
  RESERVATION_NOT_FOUND: 'RESERVATION_NOT_FOUND',

  // Conflict (409)
  CONFLICT: 'CONFLICT',
  DUPLICATE_KEY: 'DUPLICATE_KEY',
  STAND_UNAVAILABLE: 'STAND_UNAVAILABLE',
  PENDING_INVITATION: 'PENDING_INVITATION',
  FK_CONSTRAINT: 'FK_CONSTRAINT',
  CONSTRAINT_VIOLATION: 'CONSTRAINT_VIOLATION',

  // Database Errors (500)
  DB_QUERY_ERROR: 'DB_QUERY_ERROR',
  DB_UNAVAILABLE: 'DB_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Operation Errors
  FETCH_ERROR: 'FETCH_ERROR',
  CREATE_ERROR: 'CREATE_ERROR',
  UPDATE_ERROR: 'UPDATE_ERROR',
  DELETE_ERROR: 'DELETE_FAILED',

  // Expired/Timeout Errors
  EXPIRED: 'EXPIRED',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
